version: '3'

networks:
  proxy:
    external: true

services:
  web:
    image: nginx:alpine
    restart: always
    labels:
      - traefik.backend=alternatecyborg_hsist
      - traefik.frontend.rule=Host:hs.alternatecyborg.io,hs.alternatecyborg.com
      - traefik.port=80
    volumes:
      - ./public_html/:/usr/share/nginx/html
      - ./conf.d/:/etc/nginx/conf.d/
    networks:
      proxy:
